return {
    'folke/which-key.nvim',
    -- event = 'VimEnter',
    opts = {
        delay = 0,
        spec = {
            { '<leader>a', group = 'AI/Claude...' },
            { '<leader>f', group = 'find...' },
            { '<leader>t', group = 'toggle...' },
            { '<leader>h', group = 'git hunks...' },
            { '<leader>g', group = 'git...' },
            { '<leader>gd', group = 'diffview...' },
            { '<leader>d', group = 'debug...' },
            { '<leader>T', group = 'test...' },
            { '<leader>c', group = 'code...' },
            { 'g',         group = 'global/go to...' },
            { 'gr',        group = 'LSP' },
            { 'gs',  group = 'surround...' },
            { 'gsa', desc = 'add surround' },
            { 'gsd', desc = 'delete surround' },
            { 'gsr', desc = 'replace surround' },
            { 'gsf', desc = 'find surround (right)' },
            { 'gsF', desc = 'find surround (left)' },
            { 'gsh', desc = 'highlight surround' },
        },
    },
}
